// Code generated by Icestudio 0.3.0
// Mon, 28 Aug 2017 15:04:00 GMT

`default_nettype none

module main (
 input vc8ec62,
 input v5e226c,
 output v65853b,
 output v8a22df,
 output [0:4] vinit
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire w6;
 wire w7;
 wire w8;
 assign w0 = vc8ec62;
 assign w1 = v5e226c;
 assign v65853b = w3;
 assign w4 = vc8ec62;
 assign w5 = v5e226c;
 assign v8a22df = w8;
 assign w4 = w0;
 assign w5 = w1;
 v2fa1b5 v50ffbe (
  .v0e28cb(w0),
  .v3ca442(w1),
  .vcbab45(w2)
 );
 v32200d v3d2402 (
  .v0e28cb(w2),
  .vcbab45(w3)
 );
 v11a6f4 v6eaab2 (
  .v0e28cb(w6),
  .v3ca442(w7),
  .vcbab45(w8)
 );
 v32200d vd43f00 (
  .v0e28cb(w4),
  .vcbab45(w6)
 );
 v32200d vaeb9a9 (
  .v0e28cb(w5),
  .vcbab45(w7)
 );
 assign vinit = 5'b00000;
endmodule

module v2fa1b5 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v2fa1b5_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module v2fa1b5_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule

module v32200d (
 input v0e28cb,
 output vcbab45
);
 wire w0;
 wire w1;
 assign w0 = v0e28cb;
 assign vcbab45 = w1;
 v32200d_vd54ca1 vd54ca1 (
  .a(w0),
  .c(w1)
 );
endmodule

module v32200d_vd54ca1 (
 input a,
 output c
);
 // NOT logic gate
 
 assign c = ~ a;
endmodule

module v11a6f4 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v11a6f4_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module v11a6f4_vf4938a (
 input a,
 input b,
 output c
);
 // AND logic gate
 
 assign c = a & b;
endmodule
