// Code generated by Icestudio 0.3.0
// Mon, 28 Aug 2017 10:11:18 GMT

`default_nettype none

module main (
 input vc88f93,
 input vfeee04,
 output v1d1963,
 output [0:3] vinit
);
 wire w0;
 wire w1;
 wire w2;
 assign v1d1963 = w0;
 assign w1 = vc88f93;
 assign w2 = vfeee04;
 v2fa1b5 v0f531d (
  .vcbab45(w0),
  .v0e28cb(w1),
  .v3ca442(w2)
 );
 assign vinit = 4'b0000;
endmodule

module v2fa1b5 (
 input v0e28cb,
 input v3ca442,
 output vcbab45
);
 wire w0;
 wire w1;
 wire w2;
 assign w0 = v0e28cb;
 assign w1 = v3ca442;
 assign vcbab45 = w2;
 v2fa1b5_vf4938a vf4938a (
  .a(w0),
  .b(w1),
  .c(w2)
 );
endmodule

module v2fa1b5_vf4938a (
 input a,
 input b,
 output c
);
 // OR logic gate
 
 assign c = a | b;
endmodule
